/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.CoastOut;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.controls.TorqueCurrentFOC;
import com.ctre.phoenix6.controls.VelocityVoltage;
import com.ctre.phoenix6.controls.VoltageOut;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N2;
import edu.wpi.first.math.system.LinearSystem;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.system.plant.LinearSystemId;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;

public class Arm extends SubsystemBase {
    /** Velocity setpoints for the flywheel. */
    public enum ArmSetpoint {
        Intake(Rotations.of(-22)),
        Stow(Rotations.of(0));

        /** The velocity target of the setpoint. */
        public final Angle Target;

        private ArmSetpoint(Angle target) {
            this.Target = target;
        }
    }

    private static final int kNumConfigAttempts = 2;

    private static final double kGearRatio = 1;

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("canivore");
    private final TalonFX arm = new TalonFX(14, kCANBus);

    /* device status signals */
    private final StatusSignal<AngularVelocity> TopIndexVelocity = arm.getVelocity(false);
    private final StatusSignal<Current> TopIndexTorqueCurrent = arm.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final MotionMagicVoltage TopIndexSetpointRequest = new MotionMagicVoltage(0);
    private final CoastOut coastRequest = new CoastOut();

    private boolean isZerod = false;

    /* Mechanism2d visualization for flywheel TopIndex */
    private final Mechanism2d TopIndexMech2d = new Mechanism2d(2, 2);
    private final MechanismLigament2d TopIndexFlywheelMech2d = TopIndexMech2d.getRoot("Intake Root TopIndex", 1, 1)
        .append(new MechanismLigament2d("Intake TopIndex", 1, 0));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        )
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        )
        .withSlot0(
            new Slot0Configs()
                .withKP(0.8)
                .withKV(0.12)
        )
        .withMotionMagic(
            new MotionMagicConfigs()
                .withMotionMagicCruiseVelocity(RotationsPerSecond.of(50))
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(200))
        );

    /** Configs for {@link #TopIndex}. */
    private final TalonFXConfiguration TopIndexConfigs = motorTalonFXInitialConfigs.clone()
        .withMotorOutput(
            motorTalonFXInitialConfigs.MotorOutput.clone()
                .withInverted(InvertedValue.CounterClockwise_Positive)
        )
        .withFeedback(
            motorTalonFXInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(1)
        )
        .withSlot0(
            motorTalonFXInitialConfigs.Slot0.clone()
                .withKP(0.8)
                .withKI(0)
                .withKD(0)
                .withKS(0)
                .withKV(0.12)
                .withKA(0)
        );

    public Arm() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = arm.getConfigurator().apply(TopIndexConfigs);
            if (status.isOK()) break;
        }


        /* set the default command to neutral output */
        setDefaultCommand(coastIntake());

        // SmartDashboard.putData("Intake TopIndex", TopIndexMech2d);
    }

    /**
     * @return The TopIndexVelocity of the flywheel
     */
    public AngularVelocity getTopIndexVelocity() {
        return TopIndexVelocity.getValue();
    }

    /**
     * @return The TopIndexTorqueCurrent of the flywheel
     */
    public Current getTopIndexTorqueCurrent() {
        return TopIndexTorqueCurrent.getValue();
    }

    /**
     * Drives the flywheel to the provided velocity setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command setTarget(Supplier<ArmSetpoint> target) {
        return run(() -> {
            if (isZerod) {
                ArmSetpoint t = target.get();
                TopIndexSetpointRequest.withPosition(t.Target);
                arm.setControl(TopIndexSetpointRequest);   
            } else {
                arm.setControl(new CoastOut());
            }         
        });
    }

    public Command zeroArm() {
        TorqueCurrentFOC stallRequest = new TorqueCurrentFOC(-13).withMaxAbsDutyCycle(0.4);
        return run(()-> {
            arm.setControl(stallRequest);
        }).until(new Trigger(()-> {
            return arm.getVelocity().getValueAsDouble() > -1 && arm.getStatorCurrent().getValueAsDouble() > 8;
        }).debounce(0.2)).andThen(runOnce(() -> {
            arm.setPosition(-23);
            arm.setControl(new CoastOut());
            isZerod = true;
        }));
    }

    /**
     * Stops driving the Intake. We use coast so no energy is used during the braking event.
     *
     * @return Command to run
     */
    public Command coastIntake() {
        return runOnce(() -> {
            arm.setControl(coastRequest);
        });
    }

    @Override
    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            TopIndexVelocity,
            TopIndexTorqueCurrent
        );

        TopIndexFlywheelMech2d.setLength(
            TopIndexVelocity.getValueAsDouble() / 100.0
        );
    }
    public void intakeDown() {
        
    }
}