/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.SoftwareLimitSwitchConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


public class Climb extends SubsystemBase{
    private static final int kNumConfigAttempts = 2;
    
    public enum climbVars{
        climb();
    }

    private final CANBus kCANBus = new CANBus("canivore");
    private final TalonFX Climber = new TalonFX(60, kCANBus);
    private final DutyCycleOut openLoopRequest = new DutyCycleOut(0);

     private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        ).withCurrentLimits(
            new CurrentLimitsConfigs()
                .withStatorCurrentLimit(Amps.of(80))
        ).withSoftwareLimitSwitch(
            new SoftwareLimitSwitchConfigs()
                .withForwardSoftLimitThreshold(90)
                .withForwardSoftLimitEnable(true)
                .withReverseSoftLimitThreshold(0)
                .withReverseSoftLimitEnable(false)
        );

     public Climb() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = Climber.getConfigurator().apply(motorTalonFXInitialConfigs);
            if (status.isOK()) break;
        }
        Climber.setPosition(0);
    }

    public void driveOpenLoop(double dutyCycle) {
        Climber.setControl(openLoopRequest.withOutput(dutyCycle));
    }

    public Command climb() {
        return run(()->driveOpenLoop(0.8));
    }
    public Command unclimb() {
        return run(()->driveOpenLoop(-0.8));
    }

     public void periodic() {
    }
}

