/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CommutationConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.SoftwareLimitSwitchConfigs;
import com.ctre.phoenix6.configs.TalonFXSConfiguration;
import com.ctre.phoenix6.controls.CoastOut;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.hardware.TalonFXS;
import com.ctre.phoenix6.signals.MotorArrangementValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


public class Indexer extends SubsystemBase{
    private static final int kNumConfigAttempts = 2;

    private final CANBus kCANBus = new CANBus("canivore");
    private final TalonFXS conveyor = new TalonFXS(15, kCANBus);
    private final TalonFX indexer = new TalonFX(31, kCANBus);
    private final DutyCycleOut openLoopRequest = new DutyCycleOut(0);
    private final CoastOut coastRequest = new CoastOut();

     private static final TalonFXSConfiguration motorTalonFXInitialConfigs = new TalonFXSConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        // ).withCurrentLimits(
        //     new CurrentLimitsConfigs()
        //         .withStatorCurrentLimit(Amps.of(80))
        ).withSoftwareLimitSwitch(
            new SoftwareLimitSwitchConfigs()
                .withForwardSoftLimitThreshold(90)
                .withForwardSoftLimitEnable(false)
                .withReverseSoftLimitThreshold(0)
                .withReverseSoftLimitEnable(false)
        ).withCommutation(new CommutationConfigs()
            .withMotorArrangement(MotorArrangementValue.Minion_JST));

     public Indexer() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = conveyor.getConfigurator().apply(motorTalonFXInitialConfigs);
            if (status.isOK()) break;
        }
        conveyor.setPosition(0);
    }

    public void driveOpenLoop(double dutyCycle) {
        conveyor.setControl(openLoopRequest.withOutput(dutyCycle));
    }
    public void overBumperToPos(double Pos) {
        conveyor.setControl(openLoopRequest.withOutput(Pos));
    }

    public Command coastOut() {
        return run(() -> {
            conveyor.setControl(coastRequest);
            indexer.setControl(coastRequest);
        });
    }

    public Command feedToShoot() {
        return run(() -> {
            openLoopRequest.withOutput(1);
            conveyor.setControl(openLoopRequest);
            indexer.setControl(openLoopRequest);
        });
    }

    public Command justMinion() {
        return run(() -> {
            openLoopRequest.withOutput(1);
            conveyor.setControl(openLoopRequest);
        });
    }

     public void periodic() {
    }
}

