/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.CoastOut;

import com.ctre.phoenix6.controls.VelocityVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N2;
import edu.wpi.first.math.system.LinearSystem;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.system.plant.LinearSystemId;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;

public class Intake extends SubsystemBase {
    /** Velocity setpoints for the flywheel. */
    public enum IntakeSetpoint {
        Intake(RotationsPerSecond.of(100)),
        Outtake(RotationsPerSecond.of(-70));

        /** The velocity target of the setpoint. */
        public final AngularVelocity TopIndexTarget;

        private IntakeSetpoint(AngularVelocity TopIndexTarget) {
            this.TopIndexTarget = TopIndexTarget;
        }
    }

    private static final int kNumConfigAttempts = 2;

    private static final double kGearRatio = 1;

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("canivore");
    private final TalonFX TopIndex = new TalonFX(20, kCANBus);

    /* device status signals */
    private final StatusSignal<AngularVelocity> TopIndexVelocity = TopIndex.getVelocity(false);
    private final StatusSignal<Current> TopIndexTorqueCurrent = TopIndex.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final VelocityVoltage TopIndexSetpointRequest = new VelocityVoltage(0);
    private final CoastOut coastRequest = new CoastOut();

    /* simulation */
    private final DCMotor TopIndexDCMotors = DCMotor.getKrakenX60Foc(1);
    private final LinearSystem<N2, N1, N2> TopIndexFlywheelSystem = LinearSystemId.createDCMotorSystem(TopIndexDCMotors, 0.0005, kGearRatio);
    private final DCMotorSim TopIndexFlywheelSim = new DCMotorSim(TopIndexFlywheelSystem, TopIndexDCMotors);

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization for flywheel TopIndex */
    private final Mechanism2d TopIndexMech2d = new Mechanism2d(2, 2);
    private final MechanismLigament2d TopIndexFlywheelMech2d = TopIndexMech2d.getRoot("Intake Root TopIndex", 1, 1)
        .append(new MechanismLigament2d("Intake TopIndex", 1, 0));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        )
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        );

    /** Configs for {@link #TopIndex}. */
    private final TalonFXConfiguration TopIndexConfigs = motorTalonFXInitialConfigs.clone()
        .withMotorOutput(
            motorTalonFXInitialConfigs.MotorOutput.clone()
                .withInverted(InvertedValue.CounterClockwise_Positive)
        )
        .withFeedback(
            motorTalonFXInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(1)
        )
        .withSlot0(
            motorTalonFXInitialConfigs.Slot0.clone()
                .withKP(0.5)
                .withKI(0)
                .withKD(0)
                .withKS(0)
                .withKV(0.12)
                .withKA(0)
        );

    public Intake() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = TopIndex.getConfigurator().apply(TopIndexConfigs);
            if (status.isOK()) break;
        }


        /* set the default command to neutral output */
        setDefaultCommand(coastIntake());

        // SmartDashboard.putData("Intake TopIndex", TopIndexMech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The TopIndexVelocity of the flywheel
     */
    public AngularVelocity getTopIndexVelocity() {
        return TopIndexVelocity.getValue();
    }

    /**
     * @return The TopIndexTorqueCurrent of the flywheel
     */
    public Current getTopIndexTorqueCurrent() {
        return TopIndexTorqueCurrent.getValue();
    }

    public Trigger getTriggerWhenNearTarget(AngularVelocity threshold) {
        return new Trigger(() -> {
            return TopIndexVelocity.isNear(RotationsPerSecond.of(TopIndexSetpointRequest.Velocity), threshold);
        });
    }

    /**
     * Drives the flywheel to the provided velocity setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command setTarget(Supplier<IntakeSetpoint> target) {
        return run(() -> {
            IntakeSetpoint t = target.get();
            TopIndexSetpointRequest.withVelocity(t.TopIndexTarget);
            TopIndex.setControl(TopIndexSetpointRequest);            
        });
    }

    /**
     * Stops driving the Intake. We use coast so no energy is used during the braking event.
     *
     * @return Command to run
     */
    public Command coastIntake() {
        return runOnce(() -> {
            TopIndex.setControl(coastRequest);
        });
    }

    @Override
    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            TopIndexVelocity,
            TopIndexTorqueCurrent
        );

        TopIndexFlywheelMech2d.setLength(
            TopIndexVelocity.getValueAsDouble() / 100.0
        );
    }

    private void startSimThread() {
        TopIndex.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        TopIndex.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var TopIndexSim = TopIndex.getSimState();

            /* First set the supply voltage of all the devices */
            TopIndexSim.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new velocity of the simulated flywheel */
            TopIndexFlywheelSim.setInputVoltage(TopIndexSim.getMotorVoltage());
            TopIndexFlywheelSim.update(deltaTime);

            /* Apply the new rotor velocity to the motors (before gear ratio) */
            TopIndexSim.setRawRotorPosition(
                Radians.of(TopIndexFlywheelSim.getAngularPositionRad() * kGearRatio)
            );
            TopIndexSim.setRotorVelocity(
                RadiansPerSecond.of(TopIndexFlywheelSim.getAngularVelocityRadPerSec() * kGearRatio)
            );
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }
}