/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.SoftwareLimitSwitchConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.PositionVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


public class OverBumper extends SubsystemBase{
    private static final int kNumConfigAttempts = 2;
    
    public enum climbVars{
        climb();
    }

    private final CANBus kCANBus = new CANBus("canivore");
    private final TalonFX overBumper = new TalonFX(55, kCANBus);
    private final DutyCycleOut openLoopRequest = new DutyCycleOut(0);
    private final PositionVoltage positionRequest = new PositionVoltage(0);

     private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        // ).withCurrentLimits(
        //     new CurrentLimitsConfigs()
        //         .withStatorCurrentLimit(Amps.of(80))
        ).withSoftwareLimitSwitch(
            new SoftwareLimitSwitchConfigs()
                .withForwardSoftLimitThreshold(90)
                .withForwardSoftLimitEnable(false)
                .withReverseSoftLimitThreshold(0)
                .withReverseSoftLimitEnable(false)
        );

     public OverBumper() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = overBumper.getConfigurator().apply(motorTalonFXInitialConfigs);
            if (status.isOK()) break;
        }
        overBumper.setPosition(0);
    }

    public void driveOpenLoop(double dutyCycle) {
        overBumper.setControl(openLoopRequest.withOutput(dutyCycle));
    }
    public void overBumperToPos(double Pos) {
        overBumper.setControl(positionRequest.withPosition(Pos));
    }
    public Command overBumperDown() {
        return run(()->driveOpenLoop(0.8));
    }
    public Command overBumperUp() {
        return run(()->driveOpenLoop(-0.8));
    }
    public Command overBumperToIntake() {
        return run(() -> overBumperToPos(90));
    }
    public Command overBumperToUp() {
        return run(() -> overBumperToPos(20));
    }

     public void periodic() {
    }
}

